# Generated by Django 2.2.4 on 2021-04-25 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_reads_app', '0003_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name='rating',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='user_login_app.User'),
        ),
    ]
