# Generated by Django 2.2.4 on 2021-04-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_reads_app', '0004_auto_20210425_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.ManyToManyField(blank=True, related_name='ratings', to='dojo_reads_app.Rating'),
        ),
    ]
