# Generated by Django 2.2.4 on 2021-04-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_reads_app', '0005_auto_20210425_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
